### ISSUE TITLE
pdfplumber.open returns AttributeError: 'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by AngusWR** [jsvine/pdfplumber#117]
```py
import pdfplumber
with pdfplumber.open("sun.pdf") as pdf:
    test = pdf.pages[0]
    print(len(test.chars))
```
```
5125
```

```py
import pdfplumber
with pdfplumber.open("cba.pdf") as pdf:
    test = pdf.pages[0]
    print(len(test.chars))
```

```
Traceback (most recent call last):
  File "C:\Users\orang\Desktop\bank_interest_rate_webscraper\testing00000000.py", line
2, in <module>
    with pdfplumber.open("cba.pdf") as pdf:
  File "C:\Users\orang\AppData\Local\Programs\Python\Python36\lib\site-packages\pdfplumber\pdf.py", line 48, in open
    return cls(open(path, "rb"), **kwargs)
  File "C:\Users\orang\AppData\Local\Programs\Python\Python36\lib\site-packages\pdfplumber\pdf.py", line 28, in __init__
    self.doc = PDFDocument(PDFParser(stream), password = password)
  File "C:\Users\orang\AppData\Local\Programs\Python\Python36\lib\site-packages\pdfminer\pdfdocument.py", line 577, in __init__
    self._initialize_password(password)
  File "C:\Users\orang\AppData\Local\Programs\Python\Python36\lib\site-packages\pdfminer\pdfdocument.py", line 603, in _initialize_password
    handler = factory(docid, param, password)
  File "C:\Users\orang\AppData\Local\Programs\Python\Python36\lib\site-packages\pdfminer\pdfdocument.py", line 303, in __init__
    self.init()
  File "C:\Users\orang\AppData\Local\Programs\Python\Python36\lib\site-packages\pdfminer\pdfdocument.py", line 310, in init
    self.init_key()
  File "C:\Users\orang\AppData\Local\Programs\Python\Python36\lib\site-packages\pdfminer\pdfdocument.py", line 323, in init_key
    self.key = self.authenticate(self.password)
  File "C:\Users\orang\AppData\Local\Programs\Python\Python36\lib\site-packages\pdfminer\pdfdocument.py", line 371, in authenticate
    password = password.encode("latin1")
AttributeError: 'bytes' object has no attribute 'encode'
```

[sun.pdf](https://github.com/jsvine/pdfplumber/files/3215132/sun.pdf)
[cba.pdf](https://github.com/jsvine/pdfplumber/files/3215133/cba.pdf)

**Comment by CapAllen** [comment]
Got a same Error just now. LOL

**Comment by luoqygit** [comment]
I had the same problem today. I solved it by adding a 'password' parameter as below:

_with pdfplumber.open("cba.pdf", password="") as pdf:_

Because I cannot access amazon cloud (I am in China, you know the Great Fire-Wall), I couldn't test it with your 'cba.pdf' file. You can try it out yourself.

**Comment by jsvine** [comment]
Fixed, merged, and pushed. Thanks!
