### ISSUE TITLE
Customizing underlying pdfminer laparams fails

### ISSUE THREAD

**Issue by frascuchon** [jsvine/pdfplumber#168]
I'm trying to customize the underlying pdfminer text extract process for better tune my text extraction pipeline by setting some `LAParams` values falling into an error:

```shell
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/biome/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/anaconda3/envs/biome/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/Users/frascuchon/recognai/pdfplumber/tests/test_laparams_customization.py", line 20, in test_load_with_custom_laparams
    print(first_page.chars)
  File "/Users/frascuchon/recognai/pdfplumber/pdfplumber/container.py", line 35, in chars
    return self.objects.get("char", [])
  File "/Users/frascuchon/recognai/pdfplumber/pdfplumber/page.py", line 66, in objects
    self._objects = self.parse_objects()
  File "/Users/frascuchon/recognai/pdfplumber/pdfplumber/page.py", line 167, in parse_objects
    process_object(obj)
  File "/Users/frascuchon/recognai/pdfplumber/pdfplumber/page.py", line 140, in process_object
    for k, v in obj.__dict__.items()
  File "/Users/frascuchon/recognai/pdfplumber/pdfplumber/page.py", line 141, in <genexpr>
    if k not in IGNORE)
KeyError: 'index'
```

You can check on your own with this code snippet:
```python
import pdfplumber

with pdfplumber.open(path, laparams=dict(line_margin=0.2)) as pdf:
    print(f"Found {len(pdf.pages)} pages")
    first_page = pdf.pages[0]
    print(first_page.chars)
```

**Comment by jsvine** [comment]
Fixed in https://github.com/jsvine/pdfplumber/commit/df00787adae64af94f899b83e5909fefd53a5574 and now available in v0.5.16.
