### ISSUE TITLE
Error while getting content of crop box

### ISSUE THREAD

**Issue by saurabh73** [jsvine/pdfplumber#39]
Getting following error while trying to extract text from CroppedPage

```
Traceback (most recent call last):
  File "D:/workbench/topcoder/cioms-pdf-json/main.py", line 27, in <module>
    print len(box_obj.chars)
  File "C:\Python27\lib\site-packages\pdfplumber\container.py", line 35, in chars
    return self.objects.get("char", [])
  File "C:\Python27\lib\site-packages\pdfplumber\page.py", line 185, in objects
    self.bbox)
  File "C:\Python27\lib\site-packages\pdfplumber\utils.py", line 302, in within_bbox
    for k,v in objs.items())
  File "C:\Python27\lib\site-packages\pdfplumber\utils.py", line 302, in <genexpr>
    for k,v in objs.items())
  File "C:\Python27\lib\site-packages\pdfplumber\utils.py", line 306, in within_bbox
    scores = n_points_intersecting_bbox(objs, bbox)
  File "C:\Python27\lib\site-packages\pdfplumber\utils.py", line 282, in n_points_intersecting_bbox
    return list(scores)
  File "C:\Python27\lib\site-packages\pdfplumber\utils.py", line 281, in <genexpr>
    scores = (obj_inside_bbox_score(obj, bbox) for obj in objs)
  File "C:\Python27\lib\site-packages\pdfplumber\utils.py", line 236, in obj_inside_bbox_score
    score = sum(point_inside_bbox(c, bbox) for c in corners)
  File "C:\Python27\lib\site-packages\pdfplumber\utils.py", line 236, in <genexpr>
    score = sum(point_inside_bbox(c, bbox) for c in corners)
  File "C:\Python27\lib\site-packages\pdfplumber\utils.py", line 226, in point_inside_bbox
    bx0, by0, bx1, by1 = map(decimalize, bbox)
ValueError: need more than 2 values to unpack
```

**Comment by saurabh73** [comment]
changing lines in def **point_inside_bbox** of **utils.py**
`bx0, by0, bx1, by1 = map(decimalize, bbox)`
to
```
 bx0, by0= map(decimalize, bbox[0])
 bx1, by1 = map(decimalize, bbox[1])
``` 

and lines in def **clip_obj**
`x0, top, x1, bottom= map(decimalize, bbox)`
to
```
x0, top= map(decimalize, bbox[0])
x1, bottom = map(decimalize, bbox[1])
```

fixes this issue for me.

**Comment by jsvine** [comment]
Thanks, @saurabh73! Do you have an example of a PDF that raised this error? I'd like to be able to incorporate it into tests.

**Comment by saurabh73** [comment]
@jsvine Sure, file attached.
[CIOMS SAMPLE - 1.pdf](https://github.com/jsvine/pdfplumber/files/1489634/CIOMS.SAMPLE.-.1.pdf)

**Comment by jsvine** [comment]
Thanks, @saurabh73! That's quite helpful. Additionally, do have an example of code that triggered this error?

**Comment by saurabh73** [comment]
```
pdf = pdfplumber.open("input/sample1.pdf")
page = pdf.pages[0]
curves = page.curves
sections = list()
for index, curve in enumerate(curves):  # remove check boxes
    if not layout_helper.is_checkbox(curve):
        sections.append(curve)

for section_index, section in enumerate(sections):
    points = list(section['points'])
    lines = layout_helper.find_lines(points) # gives list of horizontal and vertical lines create by points

boxes = layout_helper.find_boxes(lines) # gives list of boxes(smallest area) created by pair of horizontal and vertical lines
for box_index, box in enumerate(boxes):
    cropped_page = page.crop(box) # this live gave error
```

**Comment by jsvine** [comment]
Unfortunately, without the `layout_helper` code, it's difficult to interpret what's going on here. In a given iteration, `box` should be a `(x0, top, x1, bottom)` tuple. It seems, from the error you've pasted above, that `box` in this code may, instead, be a nested `((x0, top), (x1, bottom))` tuple.

Is that the case?

If so, try changing `layout_helper.find_boxes` to return `(x0, top, x1, bottom)`.

And if that does explain what's going on, I should add a more informative `Exception` to the `page.crop` method when it receives something that isn't `(x0, top, x1, bottom)`.

**Comment by saurabh73** [comment]
@jsvine Thank you for the catch, changing box list to (x0, top, x1, bottom) fix this issue. 
Sorry I completely missed that.

**Comment by jsvine** [comment]
No worries!
