### ISSUE TITLE
pdfminer dependency chain? 

### ISSUE THREAD

**Issue by jsfenfen** [jsvine/pdfplumber#6]
Installing v0.3.1 on python 2.7.11 using 'pip install pdfplumber' it freaked out about pdfminer.utils being missing. Maybe the most recent version of pdfminer.six (there's a new version as of 2/2 ) doesn't explicitly include pdfminer as a dependency? I didn't bother to run it down, I just added pdfminer by hand and it worked. 

Collecting pdfplumber
  Downloading pdfplumber-0.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/46/sq_lbdj547v5mrx7xzfldg0h0000gn/T/pip-build-VgxS3_/pdfplumber/setup.py", line 5, in <module>
        version = __import__("pdfplumber").VERSION
      File "/private/var/folders/46/sq_lbdj547v5mrx7xzfldg0h0000gn/T/pip-build-VgxS3_/pdfplumber/pdfplumber/__init__.py", line 1, in <module>
        from pdfplumber.pdf import PDF
      File "/private/var/folders/46/sq_lbdj547v5mrx7xzfldg0h0000gn/T/pip-build-VgxS3_/pdfplumber/pdfplumber/pdf.py", line 1, in <module>
        from pdfplumber.container import Container
      File "/private/var/folders/46/sq_lbdj547v5mrx7xzfldg0h0000gn/T/pip-build-VgxS3_/pdfplumber/pdfplumber/container.py", line 2, in <module>
        from pdfplumber import helpers, utils
      File "/private/var/folders/46/sq_lbdj547v5mrx7xzfldg0h0000gn/T/pip-build-VgxS3_/pdfplumber/pdfplumber/utils.py", line 2, in <module>
        from pdfminer.utils import PDFDocEncoding
    ImportError: No module named pdfminer.utils
    
    ----------------------------------------

**Comment by jsvine** [comment]
Ah, I'm just a dummy is all! Tried to get too fancy with setup.py. Just pushed a fix. Try `pip install pdfplumber --no-cache` to install the latest. Lemme know if that works. Thanks for flagging!

**Comment by jsfenfen** [comment]
Seems to work.
