### ISSUE TITLE
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'

### ISSUE THREAD

**Issue by keirlee** [jsvine/pdfplumber#61]
**The stacktrace `is**`
Traceback (most recent call last):
  File "tongchengVocationSpider.py", line 67, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "pdfplumber\__init__.py", line 1, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "pdfplumber\pdf.py", line 6, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "pdfminer\pdfdocument.py", line 12, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "Crypto\Cipher\__init__.py", line 3, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "Crypto\Cipher\_mode_ecb.py", line 46, in <module>
  File "Crypto\Util\_raw_api.py", line 258, in load_pycryptodome_raw_lib
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.pyd': cannot load library G:\WORKSP~1\QUNAER~1\qunaer\qunaer\qunaer\dist\TONGCH~1\Crypto\Util\..\Cipher\_raw_ecb.pyd: error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'G:\\WORKSP~1\\QUNAER~1\\qunaer\\qunaer\\qunaer\\dist\\TONGCH~1\\Crypto\\Util\\..\\Cipher\\_raw_ecb.pyd'
Failed to execute script tongchengVocationSpider

my python is 2.7.14 and my os is win10 64bit

**Comment by jsvine** [comment]
It looks like this `pycryptodome` issue may be helpful: https://github.com/Legrandin/pycryptodome/issues/155
