### ISSUE TITLE
OverflowError: Python int too large to convert to C long on certain pdfs

### ISSUE THREAD

**Issue by RakshaBM** [jsvine/pdfplumber#78]
I am facing an issue where the below error is thrown only for a certain pdf document.

```
Traceback (most recent call last):
  File "/Users/rakshabm/Documents/Python/pdf_plumber.py", line 28, in <module>
    print(fetch_words("/Users/rakshabm/Downloads/138611511.pdf"))
  File "/Users/rakshabm/Documents/Python/pdf_plumber.py", line 14, in fetch_words
    print(page.objects)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pdfplumber/page.py", line 65, in objects
    self._objects = self.parse_objects()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pdfplumber/page.py", line 128, in parse_objects
    for obj in self.layout._objs:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pdfplumber/page.py", line 59, in layout
    self._layout = self.pdf.process_page(self.page_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pdfplumber/pdf.py", line 45, in process_page
    self.interpreter.process_page(page)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 852, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 862, in render_contents
    self.init_resources(resources)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 362, in init_resources
    self.fontmap[fontid] = self.rsrcmgr.get_font(objid, spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 200, in get_font
    font = PDFType3Font(self, spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pdfminer/pdffont.py", line 622, in __init__
    PDFSimpleFont.__init__(self, descriptor, widths, spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pdfminer/pdffont.py", line 547, in __init__
    self.cid2unicode = EncodingDB.get_encoding(name, diff)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pdfminer/encodingdb.py", line 61, in get_encoding
    cid2unicode[cid] = name2unicode(x.name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pdfminer/encodingdb.py", line 21, in name2unicode
    return six.unichr(int(m.group(0)))
OverflowError: Python int too large to convert to C long
```
This is the error that is thrown for the below piece of code
```
pdf = pdfplumber.open(pdf_path)
page = pdf.pages[0]
page.objects
```

**Comment by jsvine** [comment]
Judging by the traceback, this appears to be an issue with [`pdfminer.six`](https://github.com/pdfminer/pdfminer.six), upon which `pdfplumber` is built.
