### ISSUE TITLE
IndexError: list index out of range when call  page.extract_text()

### ISSUE THREAD

**Issue by tpbluesky** [jsvine/pdfplumber#97]
Environment :
```
python : 3.7.1
pdfplumber: 0.5.11
pdfminer.six: 20181108
```
I'm trying to extract text from page two of this pdf([info.PDF](https://github.com/jsvine/pdfplumber/files/2723820/info.PDF)), but i get IndexError, what's wrong?

```
    with pdfplumber.open(path) as pdf: 
        pdf.pages[1].extract_text()
```
The error info is like :
```
Traceback (most recent call last):
  File "D:/Financial Analysis/doc_fts/pdf2html.py", line 1946, in <module>
    print(pdf.pages[1].extract_text())
  File "D:\Financial Analysis\doc_fts_venv\lib\site-packages\pdfplumber\page.py", line 192, in extract_text
    return utils.extract_text(self.chars,
  File "D:\Financial Analysis\doc_fts_venv\lib\site-packages\pdfplumber\container.py", line 35, in chars
    return self.objects.get("char", [])
  File "D:\Financial Analysis\doc_fts_venv\lib\site-packages\pdfplumber\page.py", line 66, in objects
    self._objects = self.parse_objects()
  File "D:\Financial Analysis\doc_fts_venv\lib\site-packages\pdfplumber\page.py", line 166, in parse_objects
    for obj in self.layout._objs:
  File "D:\Financial Analysis\doc_fts_venv\lib\site-packages\pdfplumber\page.py", line 60, in layout
    self._layout = self.pdf.process_page(self.page_obj)
  File "D:\Financial Analysis\doc_fts_venv\lib\site-packages\pdfplumber\pdf.py", line 45, in process_page
    self.interpreter.process_page(page)
  File "D:\Financial Analysis\doc_fts_venv\lib\site-packages\pdfminer\pdfinterp.py", line 852, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "D:\Financial Analysis\doc_fts_venv\lib\site-packages\pdfminer\pdfinterp.py", line 862, in render_contents
    self.init_resources(resources)
  File "D:\Financial Analysis\doc_fts_venv\lib\site-packages\pdfminer\pdfinterp.py", line 362, in init_resources
    self.fontmap[fontid] = self.rsrcmgr.get_font(objid, spec)
  File "D:\Financial Analysis\doc_fts_venv\lib\site-packages\pdfminer\pdfinterp.py", line 197, in get_font
    font = PDFTrueTypeFont(self, spec)
  File "D:\Financial Analysis\doc_fts_venv\lib\site-packages\pdfminer\pdffont.py", line 594, in __init__
    PDFSimpleFont.__init__(self, descriptor, widths, spec)
  File "D:\Financial Analysis\doc_fts_venv\lib\site-packages\pdfminer\pdffont.py", line 560, in __init__
    CMapParser(self.unicode_map, BytesIO(strm.get_data())).run()
  File "D:\Financial Analysis\doc_fts_venv\lib\site-packages\pdfminer\cmapdb.py", line 287, in run
    self.nextobject()
  File "D:\Financial Analysis\doc_fts_venv\lib\site-packages\pdfminer\psparser.py", line 616, in nextobject
    self.do_keyword(pos, token)
  File "D:\Financial Analysis\doc_fts_venv\lib\site-packages\pdfminer\cmapdb.py", line 393, in do_keyword
    self.cmap.add_cid2unichr(s1+i, code[i])
IndexError: list index out of range
```

**Comment by jsvine** [comment]
Based on the last line of traceback you posted, it seems the issue stems from this line in `pdfminer.six`: https://github.com/pdfminer/pdfminer.six/blob/master/pdfminer/cmapdb.py#L393

I'm not familiar enough with `pdfminer.six`'s internals to know definitively the precise cause/solution, but it's worth trying to reproduce the error using just `pdfminer.six` (rather than `pdfplumber`) and submitting an issue there.
